apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-app
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source: 
    repoURL: https://github.com/Jojoooo1/argo-deploy-applications-infra-gke.git
    targetRevision: main
    path: overlays/test/applications/shared

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
